name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE_URL: http://137.74.133.131

      - name: Copy files to OVH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 137.74.133.131
          username: ubuntu
          key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          source: out/
          target: /tmp/frontend-deploy
          strip_components: 1

      - name: Activate on Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 137.74.133.131
          username: ubuntu
          key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/ciblorgasport
            sudo mv /tmp/frontend-deploy /var/www/ciblorgasport
            sudo chown -R www-data:www-data /var/www/ciblorgasport
            sudo nginx -t && sudo systemctl reload nginx
